---
title: "Dreaft Report"
author: "Ayato Tanemura"
date: "`r Sys.Date()`"
output: pdf_document
---

# Unconditional Means Model

* The composit model is :

Issues = 24.84 + e

* Estimate of fixed effect :

The initial status of Issues at occasion 0 is 24.84 (p = 0) at 0.01 level of significance.

# Unconditional Growth model

* The composit model :

Level1 : Issues = a + b * Time_1 + j
Level2 : a = 1.00 + y_0i, b = 6.81 + y_1i

Issues = 1.00 + 6.81 * Time_1 + e (With composite residual : e = y_0i + y_1i * Time_1 + j)

* Estimate of fixed effect

1. The estimated initial Issues is 2.60 (p-vale = 0.35). However, it is non-significant at 0.01 level of significance.

2. The rate of change at the Time_1 0 is 0.11 (p-vale = 0) at 0.01 level of significance.

# Members, Commits, Watchers, and Pull Requests

* Estimate of Fixed effect

1. The estimated initial Issues controlling for members, commits, watchers, and pull requests is -1.64 (p > 0.01). However, it is non-significant at 0.01 level of significance.

2. The estimated differential in initial Issues for one member difference in Members controlling for other predictors at the initial stage is 0.28 (p<0.01) at 0.01 level of significance.

3. The estimate rate of change in Issues controlling for Members, Commits, Watchers, and Pull Requests is 2.66 (p<0.05)  at 0.05 level of significance.

4. The estimated differential in initial Issues for one commit difference in Commits controlling for other predictors at the initial stage is 0.049 (p<0.01) at 0.01 level of significance.

5. The estimated differential in initial Issues for one watcher difference in Watchers controlling for other predictors at the initial stage is 0.0098 (p<0.05) at 0.05 level of significance.

6. The estimated differential in initial Issues for one pull request difference in Pull Request controlling for other predictors at the initial stage is -0.091 (p<0.01) at 0.01 level of significance.

7. The estimated differential in the rate of change in Issues of Members is -0.019  (p > 0.05). However, it is indistinguishable since the p value is 0.60.

8. The estimated differential in the rate of change in Issues of Commits is 0.0059  (p < 0.01) at 0.01 level of significance.

9. The estimated differential in the rate of change in Issues of Watchers is 0.0070  (p < 0.01) at 0.01 level of significance.

10. The estimated differential in the rate of change in Issues of Pull Request is 0.0024  (p < 0.01) at 0.01 level of significance.


# Members(only initial status), Commits, Watchers, and Pull Requests

1. The estimated initial Issues controlling for members, commits, watchers, and pull requests is -1.58 (p > 0.01). However, it is non-significant at 0.01 level of significance.

2. The estimated differential in initial Issues for one member difference in Members controlling for other predictors at the initial stage is 0.28 (p<0.01) at 0.01 level of significance.

3. The estimated differential in initial Issues for one commit difference in Commits controlling for other predictors at the initial stage is 0.049 (p<0.01) at 0.01 level of significance.

4. The estimate rate of change in Issues controlling for Members, Commits, Watchers, and Pull Requests is 2.41 (p<0.05)  at 0.05 level of significance.

5. The estimated differential in initial Issues for one watcher difference in Watchers controlling for other predictors at the initial stage is 0.0097 (p<0.05) at 0.05 level of significance.

6. The estimated differential in initial Issues for one pull request difference in Pull Request controlling for other predictors at the initial stage is -0.092 (p<0.01) at 0.01 level of significance.

7. The estimated differential in the rate of change in Issues of Commits is 0.0059  (p < 0.01) at 0.01 level of significance.

8. The estimated differential in the rate of change in Issues of Watchers is 0.0070  (p < 0.01) at 0.01 level of significance.

9. The estimated differential in the rate of change in Issues of Pull Request is 0.0024  (p < 0.01) at 0.01 level of significance.

# Members(only initial status), Commits, Watchers, and Log(Pull Requests)

1. The estimated initial Issues controlling for members, commits, watchers, and pull requests is -1.96 (p > 0.05). However, it is non-significant at 0.05 level of significance.

2. The estimated differential in initial Issues for one member difference in Members controlling for other predictors at the initial stage is 0.19 (p<0.05) at 0.05 level of significance.

3. The estimated differential in initial Issues for one commit difference in Commits controlling for other predictors at the initial stage is 0.035 (p<0.01) at 0.01 level of significance.

4. The estimate rate of change in Issues controlling for Members, Commits, Watchers, and Log(Pull Requests) is 0.51 (p>0.05). However, it is non-significant at 0.05 level of significance.

5. The estimated differential in initial Issues for one watcher difference in Watchers controlling for other predictors at the initial stage is 0.0060 (p>0.05). However, it is non-significant at 0.05 level of significance.

6. The estimated differential in initial Issues for one pull request difference in Log(Pull Request) controlling for other predictors at the initial stage is 7.82 (p<0.01) at 0.01 level of significance.

7. The estimated differential in the rate of change in Issues of Commits is 0.0099  (p < 0.01) at 0.01 level of significance.

8. The estimated differential in the rate of change in Issues of Watchers is 0.0091  (p < 0.01) at 0.01 level of significance.

9. The estimated differential in the rate of change in Issues of Pull Request is 0.25 (p>0.05). However, it is non-significant at 0.05 level of significance.

# Members(only initial status), Commits, Watchers, and Log(Pull Requests) (Only initial status)

1. The estimated initial Issues controlling for members, commits, watchers, and pull requests is -2.16 (p > 0.05). However, it is non-significant at 0.05 level of significance.

2. The estimated differential in initial Issues for one member difference in Members controlling for other predictors at the initial stage is 0.19 (p<0.05) at 0.05 level of significance.

3. The estimated differential in initial Issues for one commit difference in Commits controlling for other predictors at the initial stage is 0.035 (p<0.01) at 0.01 level of significance.

4. The estimate rate of change in Issues controlling for Members, Commits, Watchers, and Log(Pull Requests) is 0.72 (p>0.05). However, it is non-significant at 0.05 level of significance.

5. The estimated differential in initial Issues for one watcher difference in Watchers controlling for other predictors at the initial stage is 0.0058 (p>0.05). However, it is non-significant at 0.05 level of significance.

6. The estimated differential in initial Issues for one pull request difference in Log(Pull Request) controlling for other predictors at the initial stage is 8.18 (p<0.01) at 0.01 level of significance.

7. The estimated differential in the rate of change in Issues of Commits is 0.010  (p < 0.01) at 0.01 level of significance.

8. The estimated differential in the rate of change in Issues of Watchers is 0.0093  (p < 0.01) at 0.01 level of significance.

# Members(only initial status), Commits, and Log(Pull Requests) (Only initial status)

1. The estimated initial Issues controlling for members, commits, watchers, and pull requests is -1.99 (p > 0.05). However, it is non-significant at 0.05 level of significance.

2. The estimated differential in initial Issues for one member difference in Members controlling for other predictors at the initial stage is 0.19 (p<0.05) at 0.05 level of significance.

3. The estimated differential in initial Issues for one commit difference in Commits controlling for other predictors at the initial stage is 0.033 (p<0.01) at 0.01 level of significance.

4. The estimate rate of change in Issues controlling for Members, Commits, Watchers, and Log(Pull Requests) is 1.34 (p>0.05). However, it is non-significant at 0.05 level of significance.

5. The estimated differential in initial Issues for one pull request difference in Log(Pull Request) controlling for other predictors at the initial stage is 8.18 (p<0.01) at 0.01 level of significance.

6. The estimated differential in the rate of change in Issues of Commits is 0.011  (p < 0.01) at 0.01 level of significance.











